In [4]:
import numpy as np
from stringart.algorithm.lines import draw_line
from stringart.preprocessing.image import resize_img, make_greyscale
from PIL import Image
from tqdm import tqdm
import cupy as cp
from numpy.lib.stride_tricks import as_strided

In [11]:
base_image = np.ones((10, 10))
x_coords = [0, 1, 2, 5]
y_coords = [1, 3, 4, 6]

# Calculate shape and strides for the strided view
shape = (len(x_coords),)  # Shape of the 1D view
strides = (base_image.strides[0] + base_image.strides[1],)  # Strides to jump to the next point

# Create the strided view
line_view = as_strided(base_image, shape=shape, strides=strides)

print("Line View:", base_image)
line_view += 1
print("Line View:", base_image)

Line View: [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Line View: [[2. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 2. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
img = np.array(Image.open("./data/tom.jpg"))
img = resize_img(img=img, radius=1400)
img = make_greyscale(img=img)

In [3]:
line = draw_line((100, 150),(1350, 1300), 0.2, mask=np.ones_like(img, dtype=bool))[0]

In [4]:
mask = np.zeros_like(img, dtype=bool)
x_coords = line[:, 0]
y_coords = line[:, 1]
mask[x_coords, y_coords] = True

In [15]:
for _ in tqdm(range(10000)):
    testvar = img[x_coords, y_coords]
    #testvar = img*img-img

100%|██████████| 10000/10000 [00:00<00:00, 43010.83it/s]


In [6]:
cp_img = cp.array(img)
cp_line = cp.array(line)
cp_x_coords = cp.array(line[:, 0])
cp_y_coords = cp.array(line[:, 1])

In [16]:
for _ in tqdm(range(10000)):
    testvar = cp_img[cp_x_coords, cp_y_coords]
    #testvar = cp_img*cp_img-cp_img

100%|██████████| 10000/10000 [00:00<00:00, 12307.71it/s]


In [29]:
parent_arr = [[1,2], [3,4], [5,6]]
child_arr = parent_arr[0]
print(child_arr)
parent_arr[0][:] = [7,8]
print(child_arr)

[1, 2]
[7, 8]


In [4]:
condensed_arr = [[1], [2], [3], [4], [5], [6]]
uncon_arr = [[condensed_arr[0], condensed_arr[1], condensed_arr[2]], [condensed_arr[3], condensed_arr[4], condensed_arr[5]]]
print(uncon_arr)
condensed_arr[2][0] = 9
print(uncon_arr)

[[[1], [2], [3]], [[4], [5], [6]]]
[[[1], [2], [9]], [[4], [5], [6]]]
